"""Add ordering to items and categories

Revision ID: 349debdd6b87
Revises: d6ada1026a7f
Create Date: 2025-05-28 21:23:57.065774

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '349debdd6b87'
down_revision: Union[str, None] = 'd6ada1026a7f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('ordering', sa.Integer(), server_default='1', nullable=True))
    op.add_column('menu_items', sa.Column('ordering', sa.Integer(), server_default='1', nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('menu_items', 'ordering')
    op.drop_column('categories', 'ordering')
    # ### end Alembic commands ###
